### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by bharatkashyap** [project-sunbird/sunbird-community#7]
Wanted to have some clarity around the current ability of the VDN platform to view a question (or a question set) as a plain HTML page (not inside the player) with a basic template which we can then export to a PDF. 
@vrayulu

**Comment by vrayulu** [comment]
@bharatkashyap - please use discussions (https://github.com/project-sunbird/sunbird-community/discussions) for posting your questions.

cc: @joel-ekstep
